default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123123
  port: 5432

development:
  <<: *default
  database: teste_ruby_jr

test:
  <<: *default
  database: teste_ruby_jr

production:
  <<: *default
  database: teste_ruby_jr
  username: teste_ruby_jr
  password: <%= ENV['DATABASE_PASSWORD'] %>
